// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTD0oilP7Uum9ccQgqHpVD0-VwdPqkO2k',
    appId: '1:780198115612:web:c8246d00536c73545b62d9',
    messagingSenderId: '780198115612',
    projectId: 'fluenta1-ebd32',
    authDomain: 'fluenta1-ebd32.firebaseapp.com',
    storageBucket: 'fluenta1-ebd32.firebasestorage.app',
    measurementId: 'G-XNGB00R96S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKX_gX2tk6QC4UrZ5OfYiSMt9j36c_IW4',
    appId: '1:780198115612:android:02217496c5da3f165b62d9',
    messagingSenderId: '780198115612',
    projectId: 'fluenta1-ebd32',
    storageBucket: 'fluenta1-ebd32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR71ToTaXP-naqOY0ffvK_DdvMNuUI0UU',
    appId: '1:780198115612:ios:c846de84a95058e95b62d9',
    messagingSenderId: '780198115612',
    projectId: 'fluenta1-ebd32',
    storageBucket: 'fluenta1-ebd32.firebasestorage.app',
    iosBundleId: 'com.example.fluenta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR71ToTaXP-naqOY0ffvK_DdvMNuUI0UU',
    appId: '1:780198115612:ios:c846de84a95058e95b62d9',
    messagingSenderId: '780198115612',
    projectId: 'fluenta1-ebd32',
    storageBucket: 'fluenta1-ebd32.firebasestorage.app',
    iosBundleId: 'com.example.fluenta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTD0oilP7Uum9ccQgqHpVD0-VwdPqkO2k',
    appId: '1:780198115612:web:45ec376dbf7f8d685b62d9',
    messagingSenderId: '780198115612',
    projectId: 'fluenta1-ebd32',
    authDomain: 'fluenta1-ebd32.firebaseapp.com',
    storageBucket: 'fluenta1-ebd32.firebasestorage.app',
    measurementId: 'G-DTD4DLCBS4',
  );
}
